insurance_app_homepage:
    path:     /
    defaults: { _controller: InsuranceAppBundle:Default:index }

registerform:
    path: /registerform
    defaults: { _controller: InsuranceAppBundle:Registration:registerform }