fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    prefix: /profile
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"


fos_user_register:
    prefix: /register
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"


fos_user_resetting:
    prefix: /resetting
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"


fos_user_change_password:
    prefix: /profile
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"




# PROFIL GENERAL HOMEPAGE
insurance_app_homepage:
    path: /
    defaults: { _controller: InsuranceAppBundle:Default:index }

# PROFIL DETAILLE USER
insurance_app_profile:
    path: /profileInfo
    defaults: { _controller: InsuranceAppBundle:Default:profile }

# EXEMPLES DE CONTRATS USER
insurance_app_plandetail1:
    path: /Plan1
    defaults: { _controller: InsuranceAppBundle:Default:plan1 }

insurance_app_plandetail2:
    path: /Plan2
    defaults: { _controller: InsuranceAppBundle:Default:plan2 }

insurance_app_plandetail3:
    path: /Plan3
    defaults: { _controller: InsuranceAppBundle:Default:plan3 }

# SOS PAGE
insurance_app_SOS:
    path: /SOS
    defaults: { _controller: InsuranceAppBundle:Default:sos }

# CHAT PAGE
insurance_app_chat:
    path: /chat
    defaults: { _controller: InsuranceAppBundle:Default:chat }

# ADD PLAN
insurance_app_addplan:
    path: /addPlan
    defaults: { _controller: InsuranceAppBundle:Default:addPlan }

insurance_app_search:
    path: /search
    defaults: { _controller: InsuranceAppBundle:Default:searchPlan }

insurance_app_qrcode:
    path: /qrcode
    defaults: { _controller: InsuranceAppBundle:Default:qrCode }

insurance_app_nearme:
    path: /nearme
    defaults: { _controller: InsuranceAppBundle:Default:nearMe }

insurance_app_planfound:
    path: /planfound
    defaults: { _controller: InsuranceAppBundle:Default:planFound }

insurance_app_purchaseplan:
    path: /purchaseplan
    defaults: { _controller: InsuranceAppBundle:Default:purchasePlan }

insurance_app_purchaseplanconf:
    path: /purchaseplanconf
    defaults: { _controller: InsuranceAppBundle:Default:purchasePlanConf }

# CLAIMS PAGE
insurance_app_claim:
    path: /claim
    defaults: { _controller: InsuranceAppBundle:Default:claim }

insurance_app_claimfilled:
    path: /claimfilled
    defaults: { _controller: InsuranceAppBundle:Default:claimfilled }

insurance_app_claimsubmit:
    path: /claimsubmit
    defaults: { _controller: InsuranceAppBundle:Default:claimsubmit }

insurance_app_claimhistory:
    path: /claimhistory
    defaults: { _controller: InsuranceAppBundle:Default:claimhistory }


insurance_app_claim:inprogress:
    path: /claiminprogress
    defaults: { _controller: InsuranceAppBundle:Default:claimInProgress }